---
kind: pipeline
type: docker
name: build-and-push

concurrency:
  limit: 1

platform:
  os: linux
  arch: amd64

steps:
  - name: build-and-push
    image: plugins/docker
    settings:
      username: antonijolorenzoni
      password: Slovenija1974
      repo: antonijolorenzoni/drone-plugin-pom-reader
      tags: latest
        
trigger:
  branch:
    - develop
  event:
    - push

